server:
    port: 8888
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: G:\SOP\my-first-springboot\src\main\resources\